# Generated by Django 4.2.5 on 2023-12-02 12:20

import ckeditor.fields
import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='BusinessPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Name (Armenian)')),
                ('image', models.ImageField(upload_to=core.models.generate_business_partner_image, verbose_name='Image')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration')),
                ('projects_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Count of projects')),
            ],
            options={
                'verbose_name': 'Business Partner',
                'verbose_name_plural': 'Business Partners',
            },
        ),
        migrations.CreateModel(
            name='JobAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Job name (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Job name (Armenian)')),
                ('image', models.ImageField(upload_to=core.models.generate_job_announcement_image, verbose_name='Image')),
                ('description_eng', ckeditor.fields.RichTextField(verbose_name='Job description (English)')),
                ('description_arm', ckeditor.fields.RichTextField(verbose_name='Job description (Armenian)')),
                ('duration_eng', models.CharField(max_length=255, verbose_name='Job duration (English)')),
                ('duration_arm', models.CharField(max_length=255, verbose_name='Job duration in (Armenian)')),
                ('assessment_desc_eng', ckeditor.fields.RichTextField(verbose_name='Assessment Service Description (English)')),
                ('assessment_desc_arm', ckeditor.fields.RichTextField(verbose_name='Assessment Service Description (Armenian)')),
                ('appraiser_requirements_eng', ckeditor.fields.RichTextField(verbose_name='Requirements to the appraiser in (English)')),
                ('appraiser_requirements_arm', ckeditor.fields.RichTextField(verbose_name='Requirements to the appraiser (Armenian)')),
                ('application_procedure_eng', ckeditor.fields.RichTextField(verbose_name='Application Procedure (English)')),
                ('application_procedure_arm', ckeditor.fields.RichTextField(verbose_name='Application Procedure (Armenian)')),
                ('about_company_eng', ckeditor.fields.RichTextField(verbose_name='About the company (English)')),
                ('about_company_arm', ckeditor.fields.RichTextField(verbose_name='About the company (Armenian)')),
                ('contacts', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contacts')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Job Announcement',
                'verbose_name_plural': 'Job Announcements',
            },
        ),
        migrations.CreateModel(
            name='OpenCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Title (Armenian)')),
                ('description_eng', ckeditor.fields.RichTextField(verbose_name='Description (English)')),
                ('description_arm', ckeditor.fields.RichTextField(verbose_name='Description (Armenian)')),
                ('requirements_eng', ckeditor.fields.RichTextField(verbose_name='Requirements to the participant (English)')),
                ('requirements_arm', ckeditor.fields.RichTextField(verbose_name='Requirements to the participant(Armenian)')),
                ('article_eng', ckeditor.fields.RichTextField(verbose_name='Article (English)')),
                ('article_arm', ckeditor.fields.RichTextField(verbose_name='Article (Armenian)')),
                ('image', models.ImageField(upload_to=core.models.generate_open_competitions_image, verbose_name='Image')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Open Competition',
                'verbose_name_plural': 'Open Competitions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Name (Armenian)')),
                ('description_eng', models.TextField(verbose_name='Description (English)')),
                ('description_arm', models.TextField(verbose_name='Description (Armenian)')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Name (Armenian)')),
                ('title_eng', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_arm', models.CharField(max_length=255, verbose_name='Title (Armenian)')),
                ('article_eng', ckeditor.fields.RichTextField(verbose_name='Article (English)')),
                ('article_arm', ckeditor.fields.RichTextField(verbose_name='Article (Armenian)')),
                ('image', models.ImageField(upload_to='program/%Y/%m', verbose_name='Main image')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Name (Armenian)')),
                ('image', models.ImageField(upload_to='report/%Y/%m', verbose_name='Image')),
                ('report_file', models.FileField(upload_to=core.models.generate_report_file, verbose_name='File')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Name (Armenian)')),
                ('position_eng', models.CharField(max_length=255, verbose_name='Position (English)')),
                ('position_arm', models.CharField(max_length=255, verbose_name='Position (Armenian)')),
                ('image', models.ImageField(upload_to=core.models.generate_staff_image, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff members',
            },
        ),
        migrations.CreateModel(
            name='ArchiveProgram',
            fields=[
                ('program_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.program')),
            ],
            options={
                'verbose_name': 'Archive Program',
                'verbose_name_plural': 'Archive Programs',
            },
            bases=('core.program',),
        ),
        migrations.CreateModel(
            name='ProgramsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.generate_program_photos, verbose_name='Image')),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_images', to='core.program')),
            ],
            options={
                'verbose_name': 'Programs Photo',
                'verbose_name_plural': 'Programs Photos',
            },
        ),
        migrations.CreateModel(
            name='ProductVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='Video Url')),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_videos', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Video',
                'verbose_name_plural': 'Product Videos',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.generate_product_images, verbose_name='Image')),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='ProductFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.generate_product_files, verbose_name='File')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Name (Armenian)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_files', to='core.product')),
            ],
            options={
                'verbose_name': 'Product File',
                'verbose_name_plural': 'Product Files',
            },
        ),
        migrations.CreateModel(
            name='OpenCompetitionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.generate_open_competition_files, verbose_name='File')),
                ('name_eng', models.CharField(max_length=255, null=True, verbose_name='Name (English)')),
                ('name_arm', models.CharField(max_length=255, null=True, verbose_name='Name (Armenian)')),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_files', to='core.opencompetition')),
            ],
            options={
                'verbose_name': 'Open Competition File',
                'verbose_name_plural': 'Open Competition Files',
            },
        ),
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.generate_banner_image, verbose_name='Image')),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='core.banner')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
            },
        ),
    ]
