# Generated by Django 4.2.5 on 2023-10-10 21:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Name (Armenian)')),
                ('image', models.ImageField(upload_to='business_partners/', verbose_name='Image')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('projects_count', models.IntegerField(verbose_name='Count of projects')),
            ],
            options={
                'verbose_name': 'Business Partner',
                'verbose_name_plural': 'Business Partners',
            },
        ),
        migrations.CreateModel(
            name='JobAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Job name (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Job name (Armenian)')),
                ('image', models.ImageField(upload_to='Jobs/', verbose_name='Image')),
                ('description_eng', ckeditor.fields.RichTextField(verbose_name='Job description (English)')),
                ('description_arm', ckeditor.fields.RichTextField(verbose_name='Job description (Armenian)')),
                ('duration_eng', models.CharField(max_length=255, verbose_name='Job duration (English)')),
                ('duration_arm', models.CharField(max_length=255, verbose_name='Job duration in (Armenian)')),
                ('assessment_desc_eng', ckeditor.fields.RichTextField(verbose_name='Assessment Service Description (English)')),
                ('assessment_desc_arm', ckeditor.fields.RichTextField(verbose_name='Assessment Service Description (Armenian)')),
                ('appraiser_requirements_eng', ckeditor.fields.RichTextField(verbose_name='Requirements to the appraiser in (English)')),
                ('appraiser_requirements_arm', ckeditor.fields.RichTextField(verbose_name='Requirements to the appraiser (Armenian)')),
                ('application_procedure_eng', ckeditor.fields.RichTextField(verbose_name='Application Procedure (English)')),
                ('application_procedure_arm', ckeditor.fields.RichTextField(verbose_name='Application Procedure (Armenian)')),
                ('about_company_eng', ckeditor.fields.RichTextField(verbose_name='About the company (English)')),
                ('about_company_arm', ckeditor.fields.RichTextField(verbose_name='About the company (Armenian)')),
                ('contacts', ckeditor.fields.RichTextField(verbose_name='Contacts')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Job Announcement',
                'verbose_name_plural': 'Job Announcements',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Name (Armenian)')),
                ('description_eng', models.TextField(verbose_name='Description (English)')),
                ('description_arm', models.TextField(verbose_name='Description (Armenian)')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_arm', models.CharField(max_length=255, verbose_name='Title (Armenian)')),
                ('prologue_eng', ckeditor.fields.RichTextField(verbose_name='Prologue (English)')),
                ('prologue_arm', ckeditor.fields.RichTextField(verbose_name='Prologue (Armenian)')),
                ('requirements_eng', ckeditor.fields.RichTextField(verbose_name='Requirements to the participant (English)')),
                ('requirements_arm', ckeditor.fields.RichTextField(verbose_name='Requirements to the participant(Armenian)')),
                ('article_eng', ckeditor.fields.RichTextField(verbose_name='Article (English)')),
                ('article_arm', ckeditor.fields.RichTextField(verbose_name='Article (Armenian)')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Name (Armenian)')),
                ('image', models.ImageField(upload_to='report/', verbose_name='Image')),
                ('report_file', models.FileField(upload_to='report_file/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_arm', models.CharField(max_length=255, verbose_name='Name (Armenian)')),
                ('position_eng', models.CharField(max_length=255, verbose_name='Position (English)')),
                ('position_arm', models.CharField(max_length=255, verbose_name='Position (Armenian)')),
                ('image', models.ImageField(upload_to='staff/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='ProgramsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='program_photos/', verbose_name='Image')),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programs')),
            ],
            options={
                'verbose_name': 'Programs Photo',
                'verbose_name_plural': 'Programs Photos',
            },
        ),
        migrations.CreateModel(
            name='ProgramFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='program_files/', verbose_name='Image')),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programs')),
            ],
            options={
                'verbose_name': 'Program File',
                'verbose_name_plural': 'Program Files',
            },
        ),
        migrations.CreateModel(
            name='ProductVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_description_eng', models.TextField(verbose_name='Video description (English)')),
                ('video_description_arm', models.TextField(verbose_name='Video description (Armenian)')),
                ('video_url', models.URLField(verbose_name='Video Url')),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name': 'Product Video',
                'verbose_name_plural': 'Product Videos',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='program_photos/', verbose_name='Image')),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='ProductFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name': 'Product File',
                'verbose_name_plural': 'Product Files',
            },
        ),
    ]
