# Generated by Django 4.2.5 on 2023-10-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_opencompetitionfiles_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opencompetitionfiles',
            name='is_active',
        ),
        migrations.AddField(
            model_name='opencompetition',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
