# Generated by Django 4.2.5 on 2023-10-16 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_opencompetitionfiles_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartners',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='businesspartners',
            name='projects_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Count of projects'),
        ),
    ]
