# Generated by Django 4.2.5 on 2023-10-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_businesspartners_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opencompetition',
            name='is_active',
        ),
        migrations.AddField(
            model_name='opencompetition',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
