# Generated by Django 4.2.5 on 2023-10-16 17:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_opencompetition_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_staff_image, verbose_name='Image'),
        ),
    ]
