# Generated by Django 4.2.5 on 2023-10-16 18:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartners',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_business_partner_image, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='jobannouncement',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_job_announcement_image, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='opencompetition',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_open_competitions_image, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='opencompetitionfiles',
            name='file',
            field=models.FileField(upload_to=core.models.generate_open_competition_files, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='productfiles',
            name='file',
            field=models.FileField(upload_to=core.models.generate_product_files, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_product_images, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='programsphoto',
            name='image',
            field=models.ImageField(upload_to=core.models.generate_program_photos, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(upload_to=core.models.generate_report_file, verbose_name='File'),
        ),
    ]
