# Generated by Django 4.2.5 on 2023-11-07 20:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_productvideos_video_description_arm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobannouncement',
            name='contacts',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contacts'),
        ),
    ]
